version: '3'

services:
  lb:
    image: haproxy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  ws1:
    image: ws:server # Assuming Dockerfile is in the same directory
    environment:
      - APPID=1111

  ws2:
    image: ws:server 
    environment:
      - APPID=2222

  ws3:
    image: ws:server
    environment:
      - APPID=3333

  ws4:
    image: ws:server
    environment:
      - APPID=4444

  rds:
    image: redis:latest
